<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ErrorRouter-Api-Development</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ErrorRouter.Application/ErrorRouter.Application.csproj" />
    <ProjectReference Include="../ErrorRouter.Contracts/ErrorRouter.Contracts.csproj" />
    <ProjectReference Include="../ErrorRouter.Infrastructure/ErrorRouter.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
  </ItemGroup>

</Project>
